### ISSUE TITLE
UK market

### ISSUE THREAD

**Issue by climaxhr** [dentologix/Market-development#1]

**Comment by climaxhr** [comment]
Ed Attenborough
very interesting person, has been involved with all dental associations in UK...

**Association of Dental Dealers in Europe (ADDE)** looks interesting for penetration

https://www.linkedin.com/in/attenborough?authType=name&authToken=oCNF
Association of Dental Dealers in Europe (ADDE)
TSB HealthTech and Medicines KTN	
Dental Laboratories Association
British Dental Industry Association
General Dental Council

**Comment by climaxhr** [comment]
https://www.bdia.org.uk/  Dental Industry Association

**Comment by climaxhr** [comment]
Dentsply Sirona
http://blueprintdental.co.uk/
https://envisiontec.com/3d-printing-industries/medical/dental/ vodeci proizvodjac 3d printera
http://meditcompany.com/ 3d scanner company

**Comment by climaxhr** [comment]
**SDI Dental Ltd**
Big Australian company with offices in several European countries
SDI is an innovative product development and dental restorative manufacturing company that is also focused on the development and wellbeing of all employees. As SDI continues to grow, career opportunities become available in areas such as;
• Research & Development
• Sales & Marketing
• Manufacturing
• Information Technology
• Finance & Administration
• Logistics
**Contact Croatian dealer **MAICO,** make good. Give free, try to be heard of in SDI main office. Ask for contact.**
**MAICO
Franje Galinca 19A 42000 VARAZDIN
Telephone 40212302826
E-Mail Address maja@maico.hr - sasha.ivanish@gmail.com**

**Comment by climaxhr** [comment]
http://www.eurodontic.co.uk/ Good candidate for partner company....lab supply oriented, no software in inventory, UK based and operated..
Angela Gilding, Sales Administrator

**Comment by climaxhr** [comment]
http://www.the-dts.co.uk/
Dental Technology Showcase, UK hosted anual showcase

**Comment by climaxhr** [comment]
http://www.dentalez.com/ OK supplyer, does not look to promising but can be investegated

**Comment by climaxhr** [comment]
https://www.dmg-dental.com/en/home/ big, promissing for distributor

**Comment by climaxhr** [comment]
http://www.kemdent.co.uk/ big, posibly best. awards 2015, 2016...

**Comment by climaxhr** [comment]
https://www.kentexpress.co.uk big

**Comment by climaxhr** [comment]
Clients, prominent, bigger...to call:
http://www.pdsdental.co.uk/ 80 employees, moder, probably would like Dentologix
**Brendan Hudson**
Brendan is the owner and founder of PDS dental laboratory and is instrumental in ensuring that all clients receive excellent customer service and of a quality that is second to none. Brendan is a registered dental technician, he attended Kitson College in 1987, and founded PDS Dental Laboratory in 1990, which has grown to a talented team of over 80 staff. Brendan has won many awards throughout the years including Dental Technician of the year 2004 and Dental Laboratory of the year 2005.

**Comment by josipcrnjac** [comment]
We have entrance in Maico (surađivao sam nešto snjima, znam šeficu i glavnog koji obilazi okolo prodavat)

**Comment by climaxhr** [comment]
**The Dental Laboratories Association**


**Back Cover £950.00
Inside Front Cover £925.00
Full Page £800.00
Half Page £540.00
Quarter Page £430.00
Eighth Page £265.00
Double Page Spread £1,450.00**
P



The Dental Laboratories Association Ltd (DLA) is a professional body for dental laboratory owners in the UK. Currently the Association has around 1000 members, over 50 of whom are affiliates. It is estimated that members of the DLA are responsible for over 80% of the dental laboratory services in the UK.

Having several interesting programs to use, specialy **dental lab journal** http://dla.org.uk/affiliates/

The Dental Lab Journal is one of the most established journals in the industry and still boasts one of the largest readerships in the profession.  Due to our live database of dental laboratories and their key personnel, we are in a position to get your latest adverts, PR and supply information directly to the people in the UK that you want to read it.

equally all advertisers who book 5 or more adverts will receive a series discount.
Media kit.
http://dla.org.uk/cms/wp-content/uploads/2015/08/DLJ-Media-Pack-2017-v2.pdf
**Inserts
Inserts are accepted loose by arrangement at a cost of £350 per
1,000, based on one A4 sheet. Prices will be confirmed on sight
of insert.**

**Comment by climaxhr** [comment]
![number_of_tehnicins](https://cloud.githubusercontent.com/assets/16859946/22765142/fdb41034-ee6e-11e6-9430-a2af5548a6c7.jpg)

**Comment by climaxhr** [comment]
http://dla.org.uk/cdt-labs/ 
**LIST OF UK LABS; NO EMAILS BUT GREAT FOR RESERCH START; SHOULD BE DATAMINED**

**Comment by climaxhr** [comment]
WHY DAMAS?
**DAMAS – the Dental Appliance Manufacturers Audit Scheme** has been set up by the DLA in order that a dental appliance manufacturer’s registration claim with the MDA can be validated by an independent body. It aims to discourage fraudulent claims by unscrupulous labs that they are satisfying the requirements of the MDD.
 
**HOW DOES DAMAS WORK?**
DAMAS sets standard management system requirements to ensure that the manufacture of custom-made dental appliances is carried out in compliance with the requirements of the MDD. These standard management system requirements are written down in the DAMAS Management System Specification and these requirements must be met by a dental appliance manufacturer who wishes to become a DAMAS certified and registered manufacturer.
